# Generated by Django 5.2.7 on 2025-10-23 05:23

import django.db.models.deletion
import novels_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('cover_image', models.ImageField(null=True, upload_to=novels_app.models.novel_cover_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novels', to='novels_app.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('episode_number', models.PositiveIntegerField(help_text='Numeric ordering for episodes')),
                ('file', models.FileField(upload_to=novels_app.models.episode_file_upload_to, validators=[novels_app.models.validate_txt_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='novels_app.novel')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('novel', 'episode_number')},
            },
        ),
    ]
