# Generated by Django 5.2.7 on 2025-10-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='about',
            field=models.TextField(default='No description available for this novel.'),
        ),
    ]
