# Generated by Django 5.2.7 on 2025-10-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels_app', '0002_novel_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
